version: 2.1

executors:
  default:
    working_directory: ~/airbnb-clone
    docker:
      - image: cimg/node:22.6.0

caches:
  - &yarn_cache airbnb-clone-v1-{{ checksum "yarn.lock" }}

commands:
  defaults:
    steps:
      - checkout
      - restore_cache:
          key: *yarn_cache
      - run:
          name: Installing Dependencies
          command: yarn install
      - save_cache:
          key: *yarn_cache
          paths:
            - ./node_modules

  typescript-command:
    steps:
      - run:
          name: Validating TypeScript
          command: yarn tsc
  linters-command:
    steps:
      - run:
          name: Running linters
          command: yarn lint

jobs:
  typescript:
    executor: default
    steps:
      - defaults
      - typescript-command
  linters:
    executor: default
    steps:
      - defaults
      - linters-command

workflows:
  main:
    jobs:
      - typescript
      - linters:
          requires:
            - typescript
